apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-playground
  title: Backstage Playground
  description: A Backstage instance to get started with Backstage.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
