name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: read # checkout

jobs:
  create-release:
    name: Release
    environment: prod
    runs-on: ubuntu-latest
    permissions:
      contents: write # publish release
      packages: write # push image
      issues: write # comment on released issues
      pull-requests: write # comment on released pull requests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn tsc
          yarn build:all
      - name: Build Image & Release
        run: |
          docker build -f packages/backend/Dockerfile --tag katharinasick/backstage-playground .
          npx semantic-release-plus
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}